version: '3.8'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - photonest-network

  web:
    image: ghcr.io/rienertobias/photonest:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - LDAP_USER_SEARCH=${LDAP_USER_SEARCH}
      - LDAP_GROUP_SEARCH=${LDAP_GROUP_SEARCH}
      - LDAP_SUPERUSER_FLAGS=${LDAP_SUPERUSER_FLAGS}
      - LDAP_USER_ATTR_FN=${LDAP_USER_ATTR_FN}
      - LDAP_USER_ATTR_LN=${LDAP_USER_ATTR_LN}
      - LDAP_USER_ATTR_EMAIL=${LDAP_USER_ATTR_EMAIL}
      - LDAP_USER_ATTR_LDROLE=${LDAP_USER_ATTR_LDROLE}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - photonest-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             (python manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} || true) &&
             gunicorn --bind 0.0.0.0:8000 photonest_server.wsgi:application"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - photonest-network

volumes:
  mysql_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  photonest-network:
    driver: bridge