# Generated by Django 5.1.7 on 2025-04-01 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10, unique=True, verbose_name='Klassenname')),
            ],
            options={
                'verbose_name': 'Schulklasse',
                'verbose_name_plural': 'Schulklassen',
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='media_uploads/', verbose_name='Mediendatei')),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Video')], max_length=5, verbose_name='Medientyp')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hochgeladen am')),
                ('is_used', models.BooleanField(default=False, verbose_name='Wird verwendet')),
                ('used_in', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verwendet in')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Verwendet am')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='photonest.schoolclass', verbose_name='Klasse')),
            ],
            options={
                'verbose_name': 'Medien-Item',
                'verbose_name_plural': 'Medien-Items',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
