# Generated by Django 5.1.7 on 2025-04-01 18:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photonest', '0002_rename_mediaitem_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#015AAA', 'blue'), ('#EE3D3C', 'red'), ('#FEC210', 'yellow'), ('#F7931D', 'orange'), ('#8BC63E', 'green')]),
        ),
    ]
