# Generated by Django 5.1.7 on 2025-04-01 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photonest', '0003_schoolclass_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='media_uploads/', verbose_name='Mediendatei')),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Video')], max_length=5, verbose_name='Medientyp')),
                ('order', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Medium',
                'verbose_name_plural': 'Medien',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='photonest.schoolclass', verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='posts', to='photonest.media', verbose_name='Medien'),
        ),
    ]
