# Generated by Django 5.1.7 on 2025-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photonest', '0005_alter_media_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='photonest/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
