# Generated by Django 5.1.7 on 2025-04-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photonest', '0006_alter_media_media_file_alter_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-uploaded_at'], 'permissions': [('favor_post', 'Can favor a post')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
