# Generated by Django 5.1.7 on 2025-05-14 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photonest', '0008_post_is_reported_post_reported_at_post_reported_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='used_from',
            field=models.ManyToManyField(blank=True, related_name='used_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
