# Generated by Django 5.1.7 on 2025-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photonest', '0009_post_used_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
